# First stage: Node.js build
FROM node:18-alpine3.17 as build

WORKDIR /app
COPY . /app

RUN npm install
RUN npx vite build

# Second stage: Ubuntu with Nginx
FROM ubuntu

RUN apt-get update
RUN apt-get install nginx -y

# Copy built files from first stage
COPY --from=build /app/dist /var/www/html/

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx
CMD ["nginx","-g","daemon off;"]